### PR TITLE
Fix: Columnar handling of duplicate column values

### LINKED ISSUE #13: Columnar Rows() incorrectly handles duplicate column values
`Columnar` is a helper to work with delimited data as columns rather than rows.

When writing the data back to e.g. a CSV file, `Columnar.Rows()` transposes the list of columns into a list of rows. However the current implementation has a bug when a column contains a duplicate value, such as the following example:

|**col1**|**col2**|**col3**|
|------|------|------|
| aaa  | bbb | ccc   |
| ddd | bbb | eee  |
| fff    | ggg | ccc |

*`col2` has the value `bbb` twice; and `col3` has the value `ccc` twice.*

Duplicate values are repeated into the same row during the translation, resulting in the following incorrect rows:

```csv
col1,col2,col3
aaa,bbb,bbb,ccc,ccc
ddd,eee
fff,ggg
```

### PR DESCRIPTION
**Pull request by thekaveman**
Closes #13.

## The bug

This was a tricky one! But a silly mistake in retrospect. The code that transforms columns into rows previously looked like (pseudocode):

```csharp
// a list of lists of the row values
rows = [[],[],[],[]]

foreach (column in columns)
{
    foreach (value in column)
    {
        rows[column.index(value)].add(value)
    }
}
```

So finding the index of `value` in the `column`, and using that to add the `value` to the end of the corresponding row list. 

Finding the index only gets the index of the first occurrence of the `value`! So when `column` contains duplicates, subsequent `value`s are appended to the same row list over and over.

## The fix

This was a really simple fix, just iterating over the column indices directly:

```csharp
rows = [[],[],[],[]]

foreach (column in columns)
{
    for (i = 0; i < column.count; i++)
    {
        rows[i].add(column[i])
    }
}
```

Tests have been added to ensure the correct behavior for duplicate column values.

### CODE REVIEW

File: tests/Data/Csv/ColumnarTests.cs [hunk 1]
```diff
@@ -220,5 +276,70 @@ public void Remove_DoesNotRemove_EmptyOrNonExistentColumns(string[] columns)
...
+            var rows = columner.Rows();
+
+            Assert.AreEqual(3, rows.Count);
+            CollectionAssert.AreEqual(new[] { "1", "a", "!" }, rows[0]);
+            CollectionAssert.AreEqual(new[] { "2", "b", "@" }, rows[1]);
+            CollectionAssert.AreEqual(new[] { "3", "c", "#" }, rows[2]);
+        }
+
+        [TestMethod]
+        public void Rows_MultiRow_Duplicates()
```
Comment (angela-tran) [inline tests/Data/Csv/ColumnarTests.cs:294]: Nice test 👍

File: tests/Data/Csv/ColumnarTests.cs [hunk 2]
```diff
@@ -220,5 +276,70 @@ public void Remove_DoesNotRemove_EmptyOrNonExistentColumns(string[] columns)
             Assert.IsTrue(columnar.Header.Contains("1"));
             Assert.IsTrue(columnar.Header.Contains("!"));
         }
+
+        [TestMethod]
+        public void Rows_MultiRow()
+        {
+            var columner = NewColumnar(_data);
```
Comment (angela-tran) [inline tests/Data/Csv/ColumnarTests.cs:283]: This typo doesn't break anything, but easy to fix

**Review by angela-tran — CHANGES_REQUESTED** [review]
This fix looks good to me! 🎉 I noticed a small typo in a variable name, so after that is fixed, I say this is ready to be merged in.

**Comment by thekaveman** [comment]
Addressed your comments @angela-tran, thanks for the catch!

Added some more doc comments, and fixed another small bug with `Columnar.Write()`: it was always using `,` as a delimiter, even for data that was delimited by something else to begin with.

Rebased on the latest `main`.

**Review by angela-tran — APPROVED** [review]
The new changes look good to me 👍
